// <auto-generated />
namespace InvoiceManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class test0002005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test0002005));
        
        string IMigrationMetadata.Id
        {
            get { return "202205192219447_test0002005"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
