// <auto-generated />
namespace InvoiceManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class test032305 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test032305));
        
        string IMigrationMetadata.Id
        {
            get { return "202205231750114_test032305"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
